# Generated by Django 5.0.6 on 2024-05-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syatemd', '0002_shiiregyosha'),
    ]

    operations = [
        migrations.CreateModel(
            name='paitent',
            fields=[
                ('patid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('patfname', models.CharField(max_length=64)),
                ('patlneme', models.CharField(max_length=64)),
                ('hokenmei', models.CharField(max_length=64)),
                ('hokenexp', models.DateField()),
            ],
        ),
    ]
