# Generated by Django 5.0.6 on 2024-06-11 03:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syatemd', '0005_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
